version: "3.6"

services:
  peripheral-manager-ethernet:
    build: .
    restart: on-failure
    network: host
    privileged: True
    volumes:
      - /var/run/dbus:/var/run/dbus
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production