version: "3.6"

services:
  peripheral-manager-ethernet:
    image: peripheral-manager-ethernet 
    restart: on-failure
    network_mode: host
    privileged: True
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
      - /var/run/dbus:/var/run/dbus
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production